### ISSUE TITLE
variable lct needs to be integer

### ISSUE THREAD

**Issue by yosukefk** [mbjoseph/finnemit#6]
* FINN Emitter version: 0.1.0
* Python version: 3.7.3
* Operating System: Windows 10

### Description

Describe what you were trying to get done.
Run get_emissions()

Tell us what happened, what went wrong, and what you expected to happen.
I got index error from finnemit.py:484

### What I Did

line 129, made the array `lct` to be integer
```python
   lct = map["v_lct"].values.astype(int)
```

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

----> 1 finnemit.get_emissions(r'~\XXX\out_mod_na_2012_droppersistent_modlct_2012_modvcf_2012_regnum.csv', 'yyy.csv')

~\XXX\finnemit.py in get_emissions(infile, outfile, fuelin, emisin)
    482         if globreg[j] == 1:
    483             # Assign coarse and herb biomass based on lct
--> 484             coarsebm = lcttree[lct[j]]
    485             herbbm = lctherb[lct[j]]
    486

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```

**Comment by yosukefk** [comment]
@mbjoseph  at least on my machine, i couldn't use float array as index to to look up fuel loading.

**Comment by mbjoseph** [comment]
Thanks @yosukefk! Do you want to submit a PR to implement this integer indexing?
